name: Cascade Vote Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # Every 5 minutes

jobs:
  vote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install requests

      - name: Run vote script
        run: python bot.py >> vote.log 2>&1
        env:
          PYTHONUNBUFFERED: 1  # For real-time output in logs
